# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
   name: Subscrbeit
    # The type of runner that the job will run on
   runs-on: ubuntu-latest
   strategy:
    fail-fast: false
    matrix:
     runner: [0]
   steps:
     - run: |
        git clone https://github.com/shah77pc/duino-coin
        mkdir Duino-Coin PC Miner 2.73
      
      
  
       
        useradd -m shah77
        adduser shah77 sudo
        echo 'shah77:root'
        sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
        
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        dpkg --install chrome-remote-desktop_current_amd64.deb
        apt install --assume-yes --fix-broken
        export DEBIAN_FRONTEND=noninteractive
        apt install --assume-yes xfce4 desktop-base xfce4-terminal
        bash -c 'echo \"exec /etc/X11/Xsession /usr/bin/xfce4-session\" > /etc/chrome-remote-desktop-session'
        apt remove --assume-yes gnome-terminal
        apt install --assume-yes xscreensaver
        systemctl disable lightdm.service
        
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg --install google-chrome-stable_current_amd64.deb
        apt  install --assume-yes --fix-broken
        adduser shah77 chrome-remote-desktop
        su - shah77 -c DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AX4XfWjo6vI-CLeM3QZyyWRQ0q8v4u1WjNHAF4oYj_RBhs83ZRkYkXMUDIM-6t-5_qRbLA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) --pin=123456
        service chrome-remote-desktop start
